---
- hosts: all
  connection: local
  gather_facts: false

  tasks:
    - ansible.builtin.include_tasks: "tasks/hetzner-cloud.yaml"

- hosts: all
  handlers:
    - name: "Restart sshd"
      ansible.builtin.systemd:
        name: "sshd"
        state: "restarted"

  tasks:
    - ansible.builtin.include_tasks: "tasks/create-worker-user.yaml"
    - ansible.builtin.include_tasks: "tasks/configure-sshd.yaml"

    - name: "Install tools and requirements"
      ansible.builtin.apt:
        update_cache: true
        name:
          - python3-requests
          - python3-apt
          - curl
          - wget
          - dnsutils
          - mtr
          - tcpdump
          - ncdu
          - jq
          - iptables
          - iptables-persistent
          - unattended-upgrades
        state: present
      become: true

    - ansible.builtin.include_tasks: "tasks/configure-fail2ban.yaml"
