---
- hosts: all
  connection: local
  gather_facts: false

  tasks:
    - ansible.builtin.include_tasks: "tasks/hetzner-cloud.yaml"

- hosts: all
  tasks:
    - ansible.builtin.include_tasks: "tasks/create-worker-user.yaml"

    - ansible.builtin.include_role:
        name: "roles/ansible-role-sshd"

    - name: "Install tools and requirements"
      ansible.builtin.apt:
        update_cache: true
        name:
          - python3-requests
          - python3-apt
          - curl
          - wget
          - dnsutils
          - mtr
          - tcpdump
          - ncdu
          - jq
          - iptables
          - iptables-persistent
          - unattended-upgrades
        state: present
      become: true

    - ansible.builtin.include_role:
        name: "roles/ansible-role-fail2ban"

  post_tasks:
    - name: "Remove labels from cloud server {{ inventory_hostname }}"
      hetzner.hcloud.hcloud_server:
        api_token: "{{ hcloud_api_token }}"

        name: "{{ inventory_hostname }}"
        labels: {}

        state: present
      when: new_server
      delegate_to: localhost
