---
- hosts: all
  connection: local
  gather_facts: false

  tasks:
    - ansible.builtin.include_tasks: "tasks/hetzner-cloud.yaml"

- hosts: all
  tasks:
    - ansible.builtin.include_tasks: "tasks/create-worker-user.yaml"

    - name: "Remove labels from cloud server {{ inventory_hostname }}"
      hetzner.hcloud.hcloud_server:
        api_token: "{{ hcloud_api_token }}"

        name: "{{ inventory_hostname }}"
        labels: {}

        state: present
      when: new_server
      delegate_to: localhost

    - ansible.builtin.include_role:
        name: "roles/ansible-role-sshd"

    - name: "Update repositories cache on systems using apt"
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'
      changed_when: false
      become: true

    - name: "Install extra packages for enterprise linux"
      ansible.builtin.package:
        name: epel-release
        state: present
      when: "ansible_distribution == 'CentOS'"
      become: true

    - ansible.builtin.include_role:
        name: "roles/ansible-role-fail2ban"

    - ansible.builtin.include_tasks: "tasks/auto-update.yaml"

    #- name: "Install unattended upgrades"
    #  ansible.builtin.apt:
    #    name:
    #      - python3-requests
    #      - python3-apt
    #      - curl
    #      - wget
    #      - dnsutils
    #      - mtr
    #      - tcpdump
    #      - ncdu
    #      - jq
    #      - iptables
    #      - iptables-persistent
    #    state: present
    #  become: true

    - ansible.builtin.include_role:
        name: "roles/ansible-role-nginx"
      when:
        - enable_ipv4  # otherwise acme.sh cannot be installed
        - install_nginx
