---
- name: "Install fail2ban"
  ansible.builtin.package:
    name:
      - fail2ban
      - python3-systemd
    state: present
  become: true

- name: "Remove default jail"
  ansible.builtin.file:
    path: "/etc/fail2ban/jail.d/defaults-debian.conf"
    state: absent
  become: true

- name: "Create sshd jail"
  ansible.builtin.template:
    src: "../templates/fail2ban-sshd.conf.j2"
    dest: "/etc/fail2ban/jail.d/sshd.conf"
  become: true

- name: "Enable and start fail2ban service"
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: yes
  become: true
