---
- name: "Restart sshd"
  ansible.builtin.systemd:
    name: "sshd"
    state: "restarted"
  become: true

- name: "Restart auditd"
  ansible.builtin.systemd:
    name: auditd
    state: restarted
  become: true
