---
commands:
  - /usr/bin/passwd
  - /usr/bin/wget
  - /usr/bin/curl
  - /usr/bin/base64
  - /bin/nc
  - /bin/ncat
  - /usr/bin/ssh
  - /usr/bin/scap
  - /usr/bin/sftp
  - /usr/bin/ftp
  - /usr/bin/socat
  - /usr/sbin/tcpdump
  - /usr/sbin/wireshark
  - /usr/sbin/tshark
  - /usr/sbin/rawshark
  - /usr/bin/rdesktop
  - /usr/bin/nmap
  - /usr/bin/mknod
  - /sbin/modprobe
  - /sbin/insmod
  - /sbin/lsmod
  - /sbin/rmmod
