---
- name: "Ensure fail2ban is installed"
  ansible.builtin.package:
    name: fail2ban
    state: present
  become: true

- name: "Ensure python3-systemd is installed"
  ansible.builtin.package:
    name: python3-systemd
    state: present
  when: "ansible_distribution in ['Ubuntu', 'Debian']"
  become: true

- name: "Remove default jail"
  ansible.builtin.file:
    path: "/etc/fail2ban/jail.d/defaults-debian.conf"
    state: absent
  # when: "ansible_distribution in ['Ubuntu', 'Debian']" #  TODO test
  become: true

- name: "Create sshd jail"
  ansible.builtin.template:
    src: fail2ban-sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    mode: "0644"
  become: true

- name: "Enable and start fail2ban service"
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
  become: true
