---
- name: "Install unattended upgrades"
  ansible.builtin.package:
    name: unattended-upgrades
    state: present
  when: ansible_pkg_mgr == 'apt'
  become: true

- name: "Install dnf-automatic"
  when: ansible_pkg_mgr == 'dnf'
  block:
    - name: "Install dnf-automatic"
      ansible.builtin.package:
        name: dnf-automatic
        state: present
      become: true

    - name: "Create dnf-automatic configuration file"
      ansible.builtin.template:
        src: dnf-automatic.conf.j2
        dest: /etc/dnf/dnf-automatic.conf
        mode: "0644"
      become: true

    - name: "Enable and start dnf-automatic timer"
      ansible.builtin.systemd:
        name: dnf-automatic.timer
        enabled: true
        state: started
      become: true
