---
- name: "Ensure the audit subsystem is installed"
  ansible.builtin.package:
    name: auditd
    state: present
  become: true

- name: "Create audit rules file"
  ansible.builtin.template:
    src: auditd.rules.j2
    dest: "/etc/audit/rules.d/audit.rules"
    owner: root
    group: root
    mode: "0660"
  notify: "Restart auditd"
  become: true

- name: "Enable and start auditd service"
  ansible.builtin.systemd:
    name: auditd
    state: started
    enabled: true
  become: true
